// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/grpc/proto/signals.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarketState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BtcPrice           float64                `protobuf:"fixed64,1,opt,name=btc_price,json=btcPrice,proto3" json:"btc_price,omitempty"`
	WindowOpenPrice    float64                `protobuf:"fixed64,2,opt,name=window_open_price,json=windowOpenPrice,proto3" json:"window_open_price,omitempty"`
	SecondsRemaining   float64                `protobuf:"fixed64,3,opt,name=seconds_remaining,json=secondsRemaining,proto3" json:"seconds_remaining,omitempty"`
	PolymarketYesPrice float64                `protobuf:"fixed64,4,opt,name=polymarket_yes_price,json=polymarketYesPrice,proto3" json:"polymarket_yes_price,omitempty"`
	PolymarketNoPrice  float64                `protobuf:"fixed64,5,opt,name=polymarket_no_price,json=polymarketNoPrice,proto3" json:"polymarket_no_price,omitempty"`
	Dvol               float64                `protobuf:"fixed64,6,opt,name=dvol,proto3" json:"dvol,omitempty"`
	BinanceBids        []float64              `protobuf:"fixed64,7,rep,packed,name=binance_bids,json=binanceBids,proto3" json:"binance_bids,omitempty"` // flattened: [price, qty, price, qty, ...]
	BinanceAsks        []float64              `protobuf:"fixed64,8,rep,packed,name=binance_asks,json=binanceAsks,proto3" json:"binance_asks,omitempty"`
	RecentTrades       []*AggTrade            `protobuf:"bytes,9,rep,name=recent_trades,json=recentTrades,proto3" json:"recent_trades,omitempty"`
	RecentLiquidations []*Liquidation         `protobuf:"bytes,10,rep,name=recent_liquidations,json=recentLiquidations,proto3" json:"recent_liquidations,omitempty"`
	FundingRate        float64                `protobuf:"fixed64,11,opt,name=funding_rate,json=fundingRate,proto3" json:"funding_rate,omitempty"`
	// Pre-computed TA from Go
	Rsi_7         float64 `protobuf:"fixed64,12,opt,name=rsi_7,json=rsi7,proto3" json:"rsi_7,omitempty"`
	Rsi_14        float64 `protobuf:"fixed64,13,opt,name=rsi_14,json=rsi14,proto3" json:"rsi_14,omitempty"`
	Rsi_30        float64 `protobuf:"fixed64,14,opt,name=rsi_30,json=rsi30,proto3" json:"rsi_30,omitempty"`
	MacdSignal    float64 `protobuf:"fixed64,15,opt,name=macd_signal,json=macdSignal,proto3" json:"macd_signal,omitempty"`
	StochK        float64 `protobuf:"fixed64,16,opt,name=stoch_k,json=stochK,proto3" json:"stoch_k,omitempty"`
	Momentum_30S  float64 `protobuf:"fixed64,17,opt,name=momentum_30s,json=momentum30s,proto3" json:"momentum_30s,omitempty"`
	Momentum_60S  float64 `protobuf:"fixed64,18,opt,name=momentum_60s,json=momentum60s,proto3" json:"momentum_60s,omitempty"`
	Momentum_120S float64 `protobuf:"fixed64,19,opt,name=momentum_120s,json=momentum120s,proto3" json:"momentum_120s,omitempty"`
	Ema_9Vs_21    float64 `protobuf:"fixed64,20,opt,name=ema_9_vs_21,json=ema9Vs21,proto3" json:"ema_9_vs_21,omitempty"`
	Atr_14        float64 `protobuf:"fixed64,21,opt,name=atr_14,json=atr14,proto3" json:"atr_14,omitempty"`
	BollingerPctB float64 `protobuf:"fixed64,22,opt,name=bollinger_pct_b,json=bollingerPctB,proto3" json:"bollinger_pct_b,omitempty"`
	HourlyTrend   float64 `protobuf:"fixed64,23,opt,name=hourly_trend,json=hourlyTrend,proto3" json:"hourly_trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketState) Reset() {
	*x = MarketState{}
	mi := &file_internal_grpc_proto_signals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketState) ProtoMessage() {}

func (x *MarketState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_signals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketState.ProtoReflect.Descriptor instead.
func (*MarketState) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_signals_proto_rawDescGZIP(), []int{0}
}

func (x *MarketState) GetBtcPrice() float64 {
	if x != nil {
		return x.BtcPrice
	}
	return 0
}

func (x *MarketState) GetWindowOpenPrice() float64 {
	if x != nil {
		return x.WindowOpenPrice
	}
	return 0
}

func (x *MarketState) GetSecondsRemaining() float64 {
	if x != nil {
		return x.SecondsRemaining
	}
	return 0
}

func (x *MarketState) GetPolymarketYesPrice() float64 {
	if x != nil {
		return x.PolymarketYesPrice
	}
	return 0
}

func (x *MarketState) GetPolymarketNoPrice() float64 {
	if x != nil {
		return x.PolymarketNoPrice
	}
	return 0
}

func (x *MarketState) GetDvol() float64 {
	if x != nil {
		return x.Dvol
	}
	return 0
}

func (x *MarketState) GetBinanceBids() []float64 {
	if x != nil {
		return x.BinanceBids
	}
	return nil
}

func (x *MarketState) GetBinanceAsks() []float64 {
	if x != nil {
		return x.BinanceAsks
	}
	return nil
}

func (x *MarketState) GetRecentTrades() []*AggTrade {
	if x != nil {
		return x.RecentTrades
	}
	return nil
}

func (x *MarketState) GetRecentLiquidations() []*Liquidation {
	if x != nil {
		return x.RecentLiquidations
	}
	return nil
}

func (x *MarketState) GetFundingRate() float64 {
	if x != nil {
		return x.FundingRate
	}
	return 0
}

func (x *MarketState) GetRsi_7() float64 {
	if x != nil {
		return x.Rsi_7
	}
	return 0
}

func (x *MarketState) GetRsi_14() float64 {
	if x != nil {
		return x.Rsi_14
	}
	return 0
}

func (x *MarketState) GetRsi_30() float64 {
	if x != nil {
		return x.Rsi_30
	}
	return 0
}

func (x *MarketState) GetMacdSignal() float64 {
	if x != nil {
		return x.MacdSignal
	}
	return 0
}

func (x *MarketState) GetStochK() float64 {
	if x != nil {
		return x.StochK
	}
	return 0
}

func (x *MarketState) GetMomentum_30S() float64 {
	if x != nil {
		return x.Momentum_30S
	}
	return 0
}

func (x *MarketState) GetMomentum_60S() float64 {
	if x != nil {
		return x.Momentum_60S
	}
	return 0
}

func (x *MarketState) GetMomentum_120S() float64 {
	if x != nil {
		return x.Momentum_120S
	}
	return 0
}

func (x *MarketState) GetEma_9Vs_21() float64 {
	if x != nil {
		return x.Ema_9Vs_21
	}
	return 0
}

func (x *MarketState) GetAtr_14() float64 {
	if x != nil {
		return x.Atr_14
	}
	return 0
}

func (x *MarketState) GetBollingerPctB() float64 {
	if x != nil {
		return x.BollingerPctB
	}
	return 0
}

func (x *MarketState) GetHourlyTrend() float64 {
	if x != nil {
		return x.HourlyTrend
	}
	return 0
}

type AggTrade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IsBuyerMaker  bool                   `protobuf:"varint,3,opt,name=is_buyer_maker,json=isBuyerMaker,proto3" json:"is_buyer_maker,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggTrade) Reset() {
	*x = AggTrade{}
	mi := &file_internal_grpc_proto_signals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggTrade) ProtoMessage() {}

func (x *AggTrade) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_signals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggTrade.ProtoReflect.Descriptor instead.
func (*AggTrade) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_signals_proto_rawDescGZIP(), []int{1}
}

func (x *AggTrade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AggTrade) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AggTrade) GetIsBuyerMaker() bool {
	if x != nil {
		return x.IsBuyerMaker
	}
	return false
}

func (x *AggTrade) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type Liquidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          string                 `protobuf:"bytes,1,opt,name=side,proto3" json:"side,omitempty"`
	Quantity      float64                `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Liquidation) Reset() {
	*x = Liquidation{}
	mi := &file_internal_grpc_proto_signals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Liquidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Liquidation) ProtoMessage() {}

func (x *Liquidation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_signals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Liquidation.ProtoReflect.Descriptor instead.
func (*Liquidation) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_signals_proto_rawDescGZIP(), []int{2}
}

func (x *Liquidation) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Liquidation) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Liquidation) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Liquidation) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type Signal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Action         string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`           // "buy_yes", "buy_no", "hold"
	Confidence     float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0-1.0
	SuggestedPrice float64                `protobuf:"fixed64,3,opt,name=suggested_price,json=suggestedPrice,proto3" json:"suggested_price,omitempty"`
	SuggestedSize  float64                `protobuf:"fixed64,4,opt,name=suggested_size,json=suggestedSize,proto3" json:"suggested_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_internal_grpc_proto_signals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_signals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_signals_proto_rawDescGZIP(), []int{3}
}

func (x *Signal) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Signal) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Signal) GetSuggestedPrice() float64 {
	if x != nil {
		return x.SuggestedPrice
	}
	return 0
}

func (x *Signal) GetSuggestedSize() float64 {
	if x != nil {
		return x.SuggestedSize
	}
	return 0
}

var File_internal_grpc_proto_signals_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_signals_proto_rawDesc = "" +
	"\n" +
	"!internal/grpc/proto/signals.proto\x12\bpolyedge\"\xcc\x06\n" +
	"\vMarketState\x12\x1b\n" +
	"\tbtc_price\x18\x01 \x01(\x01R\bbtcPrice\x12*\n" +
	"\x11window_open_price\x18\x02 \x01(\x01R\x0fwindowOpenPrice\x12+\n" +
	"\x11seconds_remaining\x18\x03 \x01(\x01R\x10secondsRemaining\x120\n" +
	"\x14polymarket_yes_price\x18\x04 \x01(\x01R\x12polymarketYesPrice\x12.\n" +
	"\x13polymarket_no_price\x18\x05 \x01(\x01R\x11polymarketNoPrice\x12\x12\n" +
	"\x04dvol\x18\x06 \x01(\x01R\x04dvol\x12!\n" +
	"\fbinance_bids\x18\a \x03(\x01R\vbinanceBids\x12!\n" +
	"\fbinance_asks\x18\b \x03(\x01R\vbinanceAsks\x127\n" +
	"\rrecent_trades\x18\t \x03(\v2\x12.polyedge.AggTradeR\frecentTrades\x12F\n" +
	"\x13recent_liquidations\x18\n" +
	" \x03(\v2\x15.polyedge.LiquidationR\x12recentLiquidations\x12!\n" +
	"\ffunding_rate\x18\v \x01(\x01R\vfundingRate\x12\x13\n" +
	"\x05rsi_7\x18\f \x01(\x01R\x04rsi7\x12\x15\n" +
	"\x06rsi_14\x18\r \x01(\x01R\x05rsi14\x12\x15\n" +
	"\x06rsi_30\x18\x0e \x01(\x01R\x05rsi30\x12\x1f\n" +
	"\vmacd_signal\x18\x0f \x01(\x01R\n" +
	"macdSignal\x12\x17\n" +
	"\astoch_k\x18\x10 \x01(\x01R\x06stochK\x12!\n" +
	"\fmomentum_30s\x18\x11 \x01(\x01R\vmomentum30s\x12!\n" +
	"\fmomentum_60s\x18\x12 \x01(\x01R\vmomentum60s\x12#\n" +
	"\rmomentum_120s\x18\x13 \x01(\x01R\fmomentum120s\x12\x1d\n" +
	"\vema_9_vs_21\x18\x14 \x01(\x01R\bema9Vs21\x12\x15\n" +
	"\x06atr_14\x18\x15 \x01(\x01R\x05atr14\x12&\n" +
	"\x0fbollinger_pct_b\x18\x16 \x01(\x01R\rbollingerPctB\x12!\n" +
	"\fhourly_trend\x18\x17 \x01(\x01R\vhourlyTrend\"\x85\x01\n" +
	"\bAggTrade\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12$\n" +
	"\x0eis_buyer_maker\x18\x03 \x01(\bR\fisBuyerMaker\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\"v\n" +
	"\vLiquidation\x12\x12\n" +
	"\x04side\x18\x01 \x01(\tR\x04side\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\"\x90\x01\n" +
	"\x06Signal\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12'\n" +
	"\x0fsuggested_price\x18\x03 \x01(\x01R\x0esuggestedPrice\x12%\n" +
	"\x0esuggested_size\x18\x04 \x01(\x01R\rsuggestedSize2E\n" +
	"\rSignalService\x124\n" +
	"\tGetSignal\x12\x15.polyedge.MarketState\x1a\x10.polyedge.SignalB.Z,github.com/ali/poly-edge/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_signals_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_signals_proto_rawDescData []byte
)

func file_internal_grpc_proto_signals_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_signals_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_signals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_signals_proto_rawDesc), len(file_internal_grpc_proto_signals_proto_rawDesc)))
	})
	return file_internal_grpc_proto_signals_proto_rawDescData
}

var file_internal_grpc_proto_signals_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_grpc_proto_signals_proto_goTypes = []any{
	(*MarketState)(nil), // 0: polyedge.MarketState
	(*AggTrade)(nil),    // 1: polyedge.AggTrade
	(*Liquidation)(nil), // 2: polyedge.Liquidation
	(*Signal)(nil),      // 3: polyedge.Signal
}
var file_internal_grpc_proto_signals_proto_depIdxs = []int32{
	1, // 0: polyedge.MarketState.recent_trades:type_name -> polyedge.AggTrade
	2, // 1: polyedge.MarketState.recent_liquidations:type_name -> polyedge.Liquidation
	0, // 2: polyedge.SignalService.GetSignal:input_type -> polyedge.MarketState
	3, // 3: polyedge.SignalService.GetSignal:output_type -> polyedge.Signal
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_signals_proto_init() }
func file_internal_grpc_proto_signals_proto_init() {
	if File_internal_grpc_proto_signals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_signals_proto_rawDesc), len(file_internal_grpc_proto_signals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_signals_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_signals_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_signals_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_signals_proto = out.File
	file_internal_grpc_proto_signals_proto_goTypes = nil
	file_internal_grpc_proto_signals_proto_depIdxs = nil
}
