# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signals.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'signals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsignals.proto\x12\x08polyedge\"\xac\x04\n\x0bMarketState\x12\x11\n\tbtc_price\x18\x01 \x01(\x01\x12\x19\n\x11window_open_price\x18\x02 \x01(\x01\x12\x19\n\x11seconds_remaining\x18\x03 \x01(\x01\x12\x1c\n\x14polymarket_yes_price\x18\x04 \x01(\x01\x12\x1b\n\x13polymarket_no_price\x18\x05 \x01(\x01\x12\x0c\n\x04\x64vol\x18\x06 \x01(\x01\x12\x14\n\x0c\x62inance_bids\x18\x07 \x03(\x01\x12\x14\n\x0c\x62inance_asks\x18\x08 \x03(\x01\x12)\n\rrecent_trades\x18\t \x03(\x0b\x32\x12.polyedge.AggTrade\x12\x32\n\x13recent_liquidations\x18\n \x03(\x0b\x32\x15.polyedge.Liquidation\x12\x14\n\x0c\x66unding_rate\x18\x0b \x01(\x01\x12\r\n\x05rsi_7\x18\x0c \x01(\x01\x12\x0e\n\x06rsi_14\x18\r \x01(\x01\x12\x0e\n\x06rsi_30\x18\x0e \x01(\x01\x12\x13\n\x0bmacd_signal\x18\x0f \x01(\x01\x12\x0f\n\x07stoch_k\x18\x10 \x01(\x01\x12\x14\n\x0cmomentum_30s\x18\x11 \x01(\x01\x12\x14\n\x0cmomentum_60s\x18\x12 \x01(\x01\x12\x15\n\rmomentum_120s\x18\x13 \x01(\x01\x12\x13\n\x0b\x65ma_9_vs_21\x18\x14 \x01(\x01\x12\x0e\n\x06\x61tr_14\x18\x15 \x01(\x01\x12\x17\n\x0f\x62ollinger_pct_b\x18\x16 \x01(\x01\x12\x14\n\x0chourly_trend\x18\x17 \x01(\x01\"Y\n\x08\x41ggTrade\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\x16\n\x0eis_buyer_maker\x18\x03 \x01(\x08\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\"R\n\x0bLiquidation\x12\x0c\n\x04side\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\"]\n\x06Signal\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x17\n\x0fsuggested_price\x18\x03 \x01(\x01\x12\x16\n\x0esuggested_size\x18\x04 \x01(\x01\x32\x45\n\rSignalService\x12\x34\n\tGetSignal\x12\x15.polyedge.MarketState\x1a\x10.polyedge.SignalB.Z,github.com/ali/poly-edge/internal/grpc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/ali/poly-edge/internal/grpc/proto'
  _globals['_MARKETSTATE']._serialized_start=28
  _globals['_MARKETSTATE']._serialized_end=584
  _globals['_AGGTRADE']._serialized_start=586
  _globals['_AGGTRADE']._serialized_end=675
  _globals['_LIQUIDATION']._serialized_start=677
  _globals['_LIQUIDATION']._serialized_end=759
  _globals['_SIGNAL']._serialized_start=761
  _globals['_SIGNAL']._serialized_end=854
  _globals['_SIGNALSERVICE']._serialized_start=856
  _globals['_SIGNALSERVICE']._serialized_end=925
# @@protoc_insertion_point(module_scope)
